[UNSLOTH]
;The first two are bnb 4-bit, so if you load these, load_in_4bit = True
;The last two are MXFP4, already pre-quantized — load_in_4bit = False
fourbit_model_1 = unsloth/gpt-oss-20b-unsloth-bnb-4bit
fourbit_model_2 = unsloth/gpt-oss-120b-unsloth-bnb-4bit
fourbit_model_3 = unsloth/gpt-oss-20b
fourbit_model_4 = unsloth/gpt-oss-120b

[LLM]
model_name = unsloth/gpt-oss-20b
device_type = cuda

[EMBEDDING]
device_type = cuda
embedding_size = 768
similarity_fn = cosine
max_token_length = 8192
model_name  = nomic-ai/nomic-embed-text-v1

[SQLITE]
filename = document_cache.db
